{% set version = "1.1.0" %}

package:
  name: pargenes
  version: {{ version }}

build:
  number: 0
  # skip: True  # [py3k]

source:
  git_url: https://github.com/BenoitMorel/ParGenes.git
  git_rev: {{ version }}
  sha256: a0d321b4f5d445908bc6fbe6ad736c63b33433254e2a63747073f17454dd1d7e

requirements:
  build:
    - {{ compiler('cxx') }}
    - bison
    - flex
    - cmake
  host:
    - python
    - gmp
    - openmpi
  run:
    - python
    - openmpi

test:
  source_files:
    - tests
  commands:
    - pargenes.py --help
    # - python tests/run_tests.py

about:
  home: https://github.com/BenoitMorel/ParGenes
  license: GNU General Public License v3.
  license_file: LICENSE
  summary: A massively parallel tool for model selection and tree inference on thousands of genes

extra:
  skip-lints:
    - uses_vcs_url
  identifiers:
    - doi:10.1101/2020.02.28.969980
