{% set version = "0.1.1" %}

package:
  name: scrapp
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/Pbdas/scrapp/archive/v{{ version }}.tar.gz
  sha256: bc1dedcc0122d8ecdd3f3a04f50cabe5a96b6f221df76d26f8c6240b11e1fbe8

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
    - zlib
    - unzip
    - wget
    - autoconf
    - automake
    - flex
    - bison
    - m4
    - cmake
    - llvm-openmp # [osx]
  host:
    - {{ mpi }}
    - python
    - numpy
    - mpi4py
    - zlib
    - llvm-openmp # [osx]
  run:
    - {{ mpi }}
    - python
    - numpy
    - mpi4py
    - zlib
    - llvm-openmp # [osx]
test:
  commands:
    - scrapp.py -h | grep "Pipeline wrapper script that calculates species counts for each branch" > /dev/null
about:
  home: https://github.com/Pbdas/scrapp
  license: GNU General Public License v3.
  license_file: LICENSE
  summary: Species Counting on Reference trees viA Phylogenetic Placements
