{% set version = "0.1.1" %}

package:
  name: scrapp
  version: {{ version }}

build:
  number: 0

source:
  git_url: https://github.com/Pbdas/scrapp.git
  git_rev: v{{ version }}
  git_depth: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
    - flex
    - bison
    - m4
    - cmake
    - llvm-openmp # [osx]
  host:
    - {{ mpi }}
    - python
    - numpy
    - mpi4py
    - zlib
    - llvm-openmp # [osx]
  run:
    - {{ mpi }}
    - python
    - numpy
    - mpi4py
    - zlib
    - llvm-openmp # [osx]
test:
  commands:
    - scrapp.py -h | grep "Pipeline wrapper script that calculates species counts for each branch" > /dev/null
about:
  home: https://github.com/Pbdas/scrapp
  license: GNU General Public License v3.
  license_file: LICENSE
  summary: Species Counting on Reference trees viA Phylogenetic Placements
